In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
maindata = pd.read_csv('Data.csv') 

In [3]:
maindata.head()

Location Social Category  PrimaryGirls  PrimaryBoys  PrimaryOverall  \
0  AHMEDABAD         General          0.00         0.00            0.00   
1  AHMEDABAD             OBC          0.64         1.10            0.89   
2  AHMEDABAD              SC          0.00         0.00            0.00   
3  AHMEDABAD              ST          5.92         5.72            5.81   
4     AMRELI         General          0.87         0.00            0.00   

   UpperGirls  UpperBoys  UpperOverall  SecondGirls  SecondBoys  SecondOverall  
0        0.00       0.00          0.00         8.02       12.34          10.54  
1        9.37       4.14          6.46        18.43       23.13          21.40  
2        0.00       4.13          1.26         0.00       10.65           6.08  
3        9.68      13.69         12.07        24.31       10.94          16.57  
4        0.00       0.00          0.00         1.56       11.80           6.97

# comparison of the all grapg

# Male and Female and school category

In [10]:
# prediction time :

In [30]:
# liner regression model:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [31]:
x = maindata[['PrimaryOverall']]
y = maindata[['PrimaryBoys' , 'PrimaryGirls']]

In [32]:

print(x_test.shape)
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)


(290, 6)
(870, 6)
(290, 3)
(870, 3)


In [33]:
linermodel = LinearRegression()

In [34]:
linermodel.fit(x_train,y_train)

LinearRegression()

In [35]:
linermodel.coef_

array([[ 0.5500617 ,  0.45501269, -0.00197819,  0.00113283, -0.00077291,
         0.00179602],
       [-0.03696277,  0.02969533,  0.554245  ,  0.45226897,  0.003067  ,
        -0.00072439],
       [ 0.01420889, -0.01437871, -0.00871414,  0.00659829,  0.58461283,
         0.42335011]])

In [36]:
linermodel.intercept_

array([-0.07838675, -0.18832986, -0.25139238])

In [37]:
linermodel.predict(x_test)[:10]

array([[ 1.31246984, -0.25063962, 10.00211075],
       [ 3.53282359, 11.21754977, 30.9463826 ],
       [ 0.25494342,  8.07299017, 29.68163204],
       [ 3.34760668, 12.79061162, 32.85365204],
       [ 1.53507131, 10.18779881, 24.64165242],
       [ 0.4193031 ,  2.42627846, 27.4620329 ],
       [ 1.1895399 , 10.38173174, 31.83491493],
       [ 0.43100039,  4.2685156 , 12.88667245],
       [-0.07838675, -0.18832986, -0.25139238],
       [ 0.24194817,  1.22164052, 13.76429929]])

In [39]:
# primary school Predication :->
x = linermodel.predict([[maindata['PrimaryOverall'].mean()]]).tolist()
print("Primary boys : ",x[0][0])
print("Primary Girls : ",x[0][1])
print("OverALL : ",(x[0][1] + x[0][0]))
print("R2 Square ", metrics.r2_score(linermodel.predict(x_test) , y_test) )
print('MEA : ',metrics.mean_absolute_error(linermodel.predict(x_test) , y_test))

C:\Users\malan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but LinearRegression is expecting 6 features as input.

In [40]:
def School_And_Gender_wise_prediction():
    # primary data
    print('Primary'.center(100,'-'))
    # train and test model split :
    x = maindata[['PrimaryOverall']]
    y = maindata[['PrimaryBoys' , 'PrimaryGirls']]
    x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=12 ,test_size=0.25 )
    
    # liner regression model called
    linermodel = LinearRegression()
    linermodel.fit(x_train,y_train)
    
    # primary school Predication mean value of the all the data :->
    x = linermodel.predict([[maindata['PrimaryOverall'].mean()]]).tolist()
    print("boys : ",x[0][0] / (x[0][1] + x[0][0]))
    print("Girls : ",x[0][1] / (x[0][1] + x[0][0]))
    print("OverALL : ",(x[0][1] + x[0][0]))
    print("R2 Square ", metrics.r2_score(linermodel.predict(x_test) , y_test) )
    print('MEA : ',metrics.mean_absolute_error(linermodel.predict(x_test) , y_test) , "\n\n")
    
    # upper Primary Data :
    print('Upper Primary'.center(100,'-'))
    x1 = maindata[['UpperOverall']]
    y1 = maindata[['UpperBoys' , 'UpperGirls']]
    x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1, random_state=4 , test_size=0.25 )
    # fir the model 
    linermodel.fit(x1_train,y1_train)
    # prediction for the data :
    x11 = linermodel.predict([[maindata['UpperOverall'].mean()]]).tolist()
    print("boys : ",x11[0][0] / (x11[0][1] + x11[0][0]))
    print("Girls : ",x11[0][1] / (x11[0][1] + x11[0][0]))
    print("OverALL : ",(x11[0][1] + x11[0][0]))
    print("R2 Square ", metrics.r2_score(linermodel.predict(x1_test) , y1_test) )
    print('MEA : ',metrics.mean_absolute_error(linermodel.predict(x1_test) , y1_test) , "\n\n")
    
    # secondary data : 
    print('Secondary'.center(100,'-'))
    x2 = maindata[['SecondOverall']]
    y2 = maindata[['SecondBoys' , 'SecondGirls']]
    x2_train, x2_test, y2_train, y2_test = train_test_split(x2,y2, random_state=12 , test_size=0.25 )
    # fir the model 
    linermodel.fit(x2_train,y2_train)
    # prediction for the data :
    x22 = linermodel.predict([[maindata['UpperOverall'].mean()]]).tolist()
    print("boys : ",x22[0][0] / (x22[0][1] + x22[0][0]))
    print("Girls : ",x22[0][1] / (x22[0][1] + x22[0][0]) )
    print("OverALL : ", x22[0][1] + x22[0][0])
    print("R2 Square ", metrics.r2_score(linermodel.predict(x2_test) , y2_test) )
    print('MEA : ',metrics.mean_absolute_error(linermodel.predict(x2_test) , y2_test) )

In [41]:
School_And_Gender_wise_prediction()

----------------------------------------------Primary-----------------------------------------------
boys :  0.49272690851899126
Girls :  0.5072730914810089
OverALL :  7.586346110083333
R2 Square  0.9542536594044685
MEA :  0.696091929884425 


-------------------------------------------Upper Primary--------------------------------------------
boys :  0.42561732399579805
Girls :  0.5743826760042019
OverALL :  15.080591899896756
R2 Square  0.956312661237577
MEA :  1.45316639026304 


---------------------------------------------Secondary----------------------------------------------
boys :  0.6126614497732403
Girls :  0.38733855022675967
OverALL :  14.822916098947713
R2 Square  0.9014130917910546
MEA :  2.5302372609141512


C:\Users\malan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\malan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\malan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [42]:
def cast_wise_prediction():
    pass

In [17]:
cast = maindata.sort_values(['Social Category']) 

In [18]:
def List_conversion(l1):
    temp = []
    for i in l1:
        if type(i) == 'list':
            for j in i:
                temp.append(j)
        else:
            temp.append(i)
    return temp

In [44]:

    general = []
    obc = []
    sc = []
    st = []
    overall = []
    temp1, temp2, temp3, temp4, temp5 = 0, 0, 0, 0, 0
    for i in range(len(maindata)):
        if maindata['Social Category'][i] == 'General':
            temp1 = maindata['PrimaryBoys'][i] + maindata['PrimaryGirls'][i] + maindata['UpperBoys'][i] + maindata['UpperGirls'][i] + maindata['SecondBoys'][i] + maindata['SecondGirls'][i]
            general.append(temp1)
        if maindata['Social Category'][i] == 'OBC':
            temp2 = maindata['PrimaryBoys'][i] + maindata['PrimaryGirls'][i] + maindata['UpperBoys'][i] + maindata['UpperGirls'][i] + maindata['SecondBoys'][i] + maindata['SecondGirls'][i]
            obc.append(temp2)
        if maindata['Social Category'][i] == 'SC':
            temp3 = maindata['PrimaryBoys'][i] + maindata['PrimaryGirls'][i] + maindata['UpperBoys'][i] + maindata['UpperGirls'][i] + maindata['SecondBoys'][i] + maindata['SecondGirls'][i]
            sc.append(temp3)
        if maindata['Social Category'][i] == 'ST':
            temp4 =  maindata['PrimaryBoys'][i] + maindata['PrimaryGirls'][i] + maindata['UpperBoys'][i] + maindata['UpperGirls'][i] + maindata['SecondBoys'][i] + maindata['SecondGirls'][i]
            st.append(temp4)
        temp5 = temp1+temp2+temp3+temp4
        overall.append(temp5)
        temp1, temp2, temp3, temp4, temp5 = 0, 0, 0, 0, 0
    # implement the lincer regression model uisgn the given data


In [45]:
zipforthecast = list(zip(general,obc,sc,st,overall))

In [46]:
cast = pd.DataFrame(zipforthecast , columns=['general' ,'obc' , 'sc' , 'st' , 'overall'])
cast

general     obc      sc      st  overall
0      20.36   56.81   14.78   70.26    20.36
1      14.23   40.88   10.36  293.09    56.81
2      63.71   55.77   51.67   82.03    14.78
3      64.73   67.63   65.66   88.33    70.26
4      60.27   35.72   46.49   79.31    14.23
..       ...     ...     ...     ...      ...
285    16.50   63.76   46.94  134.50    71.81
286    32.75   42.61   28.03   40.20    57.83
287     0.00   75.84    0.00   55.66   121.91
288    21.04  112.91   90.44  104.27    40.68
289    28.24   21.40  104.80   43.13    89.75

[290 rows x 5 columns]

In [47]:
cast.sort_values('overall' , inplace=True)

In [48]:
t = LinearRegression()

In [49]:
y3= cast[['overall']]
x3 = cast[['general' ,'obc' , 'sc' , 'st']]

In [50]:
x3_train, x3_test, y3_train, y3_test = train_test_split(x3,y3, random_state=2 , test_size=0.25 )

In [51]:
print(x3_test.shape)
print(x3_train.shape)
print(y3_test.shape)
print(y3_train.shape)

(73, 4)
(217, 4)
(73, 1)
(217, 1)


In [52]:
t.fit(x3_train,y3_train)

LinearRegression()

In [53]:
predcast=t.predict(x3_train)

In [54]:
metrics.r2_score(predcast, y3_train)

-162.80484100299725

In [55]:
# polynomial regression

In [56]:
df = pd.read_csv('Data.csv').sort_values('Location')
df.head()

Location Social Category  PrimaryGirls  PrimaryBoys  PrimaryOverall  \
0    AHMEDABAD         General          0.00         0.00            0.00   
633  AHMEDABAD             OBC         18.12        18.26           18.19   
632  AHMEDABAD         General          0.00         0.00            0.00   
764  AHMEDABAD         General          9.23        12.54           11.02   
765  AHMEDABAD             OBC          0.00         0.00            0.00   

     UpperGirls  UpperBoys  UpperOverall  SecondGirls  SecondBoys  \
0          0.00       0.00          0.00         8.02       12.34   
633       26.75      19.81         22.98        35.95       39.83   
632        0.00       0.00          0.00         0.00        1.50   
764       12.00      12.73         12.40        12.77       21.93   
765        0.43       0.00          0.00        16.72       24.65   

     SecondOverall  
0            10.54  
633          38.35  
632           0.42  
764          18.05  
765          21.60

In [57]:
y = df[['PrimaryOverall',  'UpperOverall' , 'SecondOverall']]
x = df[['PrimaryBoys' ,'PrimaryGirls' ,'UpperBoys' ,'UpperGirls','SecondBoys' , 'SecondGirls']]

In [58]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=12, test_size=0.25)

In [59]:
from sklearn.preprocessing import PolynomialFeatures

In [60]:
poly = PolynomialFeatures(degree=1)
poly.fit(x_train)
x_train_poly = poly.transform(x_train)
x_test_poly = poly.transform(x_test)

lr = LinearRegression()
lr.fit(x_train_poly,y_train)

prediction = lr.predict(x_test_poly)
print(metrics.r2_score(prediction , y_test),"   ",metrics.mean_absolute_error(prediction, y_test),"    ", lr.score(x_test_poly , y_test))

0.9975564896645664     0.2310586705071315      0.9975938672878865


In [61]:
pred = lr.predict([[ df['PrimaryBoys'].mean() , df['PrimaryGirls'].mean() , df['UpperBoys'].mean() , df['UpperGirls'].mean() , df['SecondBoys'].mean() , df['SecondGirls'].mean() , 1.12 ]])

In [62]:
pred

array([[ 4.95564532, 15.75368072, 12.2275259 ]])